# Generated by Django 3.2.8 on 2021-10-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cariculam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
