# Generated by Django 3.2.8 on 2021-10-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cariculam', '0002_lesson_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='paid',
        ),
    ]
