# Generated by Django 3.2.8 on 2021-10-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
