# Generated by Django 3.2.8 on 2021-10-29 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_profile_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentreview',
            name='value',
        ),
    ]
