# Generated by Django 3.2.8 on 2021-10-28 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0004_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='property_type',
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
