# Generated by Django 3.2.8 on 2021-10-28 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignment', '0002_auto_20211028_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assignment_ans',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='user',
        ),
        migrations.CreateModel(
            name='AssignmentSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_ans', models.FileField(blank=True, null=True, upload_to='assinment_ans')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignment_mark', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
