# Generated by Django 3.2.8 on 2021-10-29 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20211028_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmit',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment'),
        ),
    ]
