# Generated by Django 3.2.8 on 2021-10-29 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_assignmentsubmit_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmit',
            name='assignment',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
